# .github/workflows/code_review.yml
name: Code Review Agent

on:
  push:
    paths:
      - '**/*.py'
  schedule:
    - cron: '0 */2 * * *'  # every 2 hours
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run code review
        run: |
          python agents/code_reviewer.py

      - name: Git pull before commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin ${{ github.ref_name }} --rebase || true

      - name: Commit flagged code (if any)
        run: |
          git add flagged_code/ review_reports/
          git commit -m "🔍 Added flagged code and review reports" || echo "No flagged files to commit"
          git push || echo "Nothing to push"
