name: Code Generation Agent

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  generate-code:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/generate-code'))

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate code
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python agents/code_generator.py

      - name: Commit generated code
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add generated_code/
          git commit -m "🤖 Added generated code"
          git push
