name: Code Generation Agent

on:
  workflow_dispatch:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  generate-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run code generator
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python agents/code_generator.py

      - name: Commit generated code
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main || true
          git add generated_code/
          git commit -m "🤖 Generated code via Code Generation Agent" || echo "Nothing to commit"
          git push || echo "Nothing to push"
